FROM oven/bun:1.2.20 AS base
WORKDIR /usr/src/app

ARG PUBLIC_HC_OAUTH_CLIENT_ID
ARG PUBLIC_HC_OAUTH_REDIRECT_URL
ARG PUBLIC_SUPABASE_URL
ARG PUBLIC_SUPABASE_ANON_KEY
ARG PUBLIC_HACKATIME_CLIENT_UID
ARG PUBLIC_HACKATIME_OAUTH_REDIRECT_URL

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

ENV PUBLIC_HC_OAUTH_CLIENT_ID=$PUBLIC_HC_OAUTH_CLIENT_ID
ENV PUBLIC_HC_OAUTH_REDIRECT_URL=$PUBLIC_HC_OAUTH_REDIRECT_URL
ENV PUBLIC_SUPABASE_URL=$PUBLIC_SUPABASE_URL
ENV PUBLIC_SUPABASE_ANON_KEY=$PUBLIC_SUPABASE_ANON_KEY
ENV PUBLIC_HACKATIME_CLIENT_UID=$PUBLIC_HACKATIME_CLIENT_UID
ENV PUBLIC_HACKATIME_OAUTH_REDIRECT_URL=$PUBLIC_HACKATIME_OAUTH_REDIRECT_URL

ENV CI=true
ENV NODE_ENV=production

RUN bun run build

FROM base AS release
ARG PUBLIC_HC_OAUTH_CLIENT_ID
ARG PUBLIC_HC_OAUTH_REDIRECT_URL
ARG PRIVATE_HC_OAUTH_CLIENT_SECRET
ARG PUBLIC_SUPABASE_URL
ARG PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG PRIVATE_HC_CDN_API_KEY
ARG PUBLIC_HACKATIME_CLIENT_UID
ARG PRIVATE_HACKATIME_CLIENT_SECRET
ARG PUBLIC_HACKATIME_OAUTH_REDIRECT_URL
ARG SLACK_BOT_TOKEN
ARG SLACK_REVIEW_CHANNEL_ID
ARG SLACK_SHOP_CHANNEL_ID
ARG SLACK_SIGNING_SECRET
ARG PRIVATE_AIRTABLE_PAT
ARG PRIVATE_AIRTABLE_BASE_ID
ARG PRIVATE_AIRTABLE_PROJECTS_TABLE
ARG SLACK_FINAL_REVIEW_CHANNEL_ID
ARG ORIGIN

COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /usr/src/app/build build
COPY --from=prerelease /usr/src/app/package.json .

ENV PUBLIC_HC_OAUTH_CLIENT_ID=$PUBLIC_HC_OAUTH_CLIENT_ID
ENV PUBLIC_HC_OAUTH_REDIRECT_URL=$PUBLIC_HC_OAUTH_REDIRECT_URL
ENV PUBLIC_SUPABASE_URL=$PUBLIC_SUPABASE_URL
ENV PUBLIC_SUPABASE_ANON_KEY=$PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV PUBLIC_HACKATIME_CLIENT_UID=$PUBLIC_HACKATIME_CLIENT_UID
ENV PUBLIC_HACKATIME_OAUTH_REDIRECT_URL=$PUBLIC_HACKATIME_OAUTH_REDIRECT_URL

USER bun

EXPOSE 3000

CMD ["bun", "run", "build/index.js"]